server:
  port: 8082

spring:
  application:
    name: shipment-service
  datasource:
    url: ${SHIPMENT_DB_URL}
    username: ${SHIPMENT_DB_USERNAME}
    password: ${SHIPMENT_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: shipment
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    schemas: shipment
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus



