server:
  port: 8081

spring:
  application:
    name: invoice-service
  datasource:
    url: ${INVOICE_DB_URL}
    username: ${INVOICE_DB_USERNAME}
    password: ${INVOICE_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: invoice
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    schemas: invoice
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN



