apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: ghcr.io/ORG/DOCUMENT_SERVICE:latest
          ports:
            - containerPort: 8083
          env:
            - name: DOCUMENT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: DOCUMENT_DB_URL
            - name: DOCUMENT_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: DOCUMENT_DB_USERNAME
            - name: DOCUMENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: DOCUMENT_DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  selector:
    app: document-service
  ports:
    - port: 80
      targetPort: 8083



