apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
        - name: invoice-service
          image: ghcr.io/ORG/INVOICE_SERVICE:latest
          ports:
            - containerPort: 8081
          env:
            - name: INVOICE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: INVOICE_DB_URL
            - name: INVOICE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: INVOICE_DB_USERNAME
            - name: INVOICE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: INVOICE_DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  selector:
    app: invoice-service
  ports:
    - port: 80
      targetPort: 8081



