apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipment-service
  template:
    metadata:
      labels:
        app: shipment-service
    spec:
      containers:
        - name: shipment-service
          image: ghcr.io/ORG/SHIPMENT_SERVICE:latest
          ports:
            - containerPort: 8082
          env:
            - name: SHIPMENT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: SHIPMENT_DB_URL
            - name: SHIPMENT_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: SHIPMENT_DB_USERNAME
            - name: SHIPMENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neon-secrets
                  key: SHIPMENT_DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-service
spec:
  selector:
    app: shipment-service
  ports:
    - port: 80
      targetPort: 8082



